# Generated by Django 2.2 on 2020-07-28 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True)),
                ('book_url', models.URLField(default='')),
                ('book_name', models.CharField(blank=True, default='', max_length=128)),
                ('subject_name', models.CharField(blank=True, default='', max_length=128)),
                ('message_html', models.TextField(default='')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=None, related_name='posts', to='groups.Group')),
                ('user', models.ForeignKey(on_delete=None, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user',)},
            },
        ),
    ]
