# Generated by Django 2.2 on 2020-07-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('message',)},
        ),
    ]
