# Generated by Django 2.2 on 2020-07-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200729_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='book_name',
            new_name='chapter_name',
        ),
    ]
