# Generated by Django 2.2 on 2020-07-29 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20200729_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='book_url',
            new_name='notes_url',
        ),
    ]
