# Generated by Django 2.2 on 2020-07-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200729_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='sem_no',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
