# Generated by Django 2.2 on 2020-07-29 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20200729_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='semester',
            new_name='which_semester',
        ),
    ]
