# Generated by Django 2.2 on 2020-07-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20200729_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-which_semester']},
        ),
    ]
